#!/usr/bin/env bash
#
#  | pur |  ||''. ||  | ||''. ||''|
#  | bsh |  ||--' ||  | ||-+' ||-
#  | bbl |  ||    `\__' ||  \ ||__|
#
# Description:              A library version of the Pure Bash Bible
# Dependencies:             bash 4+
# Optionnal dependencies:   none
# Author:                   gawlk
# Contributors:             none

# ---
# STRINGS
# ---

# Trim leading and trailing white-space from string
pure.trim_string() {
    # Usage: trim_string "   example   string    "
    : "${1#"${1%%[![:space:]]*}"}"
    : "${_%"${_##*[![:space:]]}"}"
    printf '%s\n' "$_"
}

# Trim all white-space from string and truncate spaces
pure.trim_all() {
    # Usage: trim_all "   example   string    "
    set -f
    set -- $*
    printf '%s\n' "$*"
    set +f
}

# Use regex on a string
pure.regex() {
    # Usage: regex "string" "regex"
    [[ $1 =~ $2 ]] && printf '%s\n' "${BASH_REMATCH[1]}"
}

# Hex color regex
pure.is_hex_color() {
    if [[ $1 =~ ^(#?([a-fA-F0-9]{6}|[a-fA-F0-9]{3}))$ ]]
    then
        printf '%s\n' "${BASH_REMATCH[1]}"
    else
        printf '%s\n' "error: $1 is an invalid color."
        return 1
    fi
}

# Split a string on a delimiter
pure.split() {
   # Usage: split "string" "delimiter"
   IFS=$'\n' read -d "" -ra arr <<< "${1//$2/$'\n'}"
   printf '%s\n' "${arr[@]}"
}

# Change a string to lowercase
pure.lower() {
    # Usage: lower "string"
    printf '%s\n' "${1,,}"
}

# Change a string to uppercase
pure.upper() {
    # Usage: upper "string"
    printf '%s\n' "${1^^}"
}

# Reverse a string case
pure.reverse_case() {
    # Usage: reverse_case "string"
    printf '%s\n' "${1~~}"
}

# Trim quotes from a string
pure.trim_quotes() {
    # Usage: trim_quotes "string"
    : "${1//\'}"
    printf '%s\n' "${_//\"}"
}

# Strip all instances of pattern from string
pure.strip_all() {
    # Usage: strip_all "string" "pattern"
    printf '%s\n' "${1//$2}"
}

# Strip first occurrence of pattern from string
pure.strip() {
    # Usage: strip "string" "pattern"
    printf '%s\n' "${1/$2}"
}

# Strip pattern from start of string
pure.lstrip() {
    # Usage: lstrip "string" "pattern"
    printf '%s\n' "${1##$2}"
}

# Strip pattern from end of string
pure.rstrip() {
    # Usage: rstrip "string" "pattern"
    printf '%s\n' "${1%%$2}"
}

# Percent-encode a string
pure.urlencode() {
    # Usage: urlencode "string"
    local LC_ALL=C
    for (( i = 0; i < ${#1}; i++ )); do
        : "${1:i:1}"
        case "$_" in
            [a-zA-Z0-9.~_-])
                printf '%s' "$_"
            ;;

            *)
                printf '%%%02X' "'$_"
            ;;
        esac
    done
    printf '\n'
}

# Decode a percent-encoded string
pure.urldecode() {
    # Usage: urldecode "string"
    : "${1//+/ }"
    printf '%b\n' "${_//%/\\x}"
}

# Check if string contains a sub-string
pure.contains_substring() {
    # Usage: contains_substring "string" "substring"
    [[ "$1" == *"$2"* ]]
}

# Check if string starts with sub-string
pure.starts_with_substring() {
    # Usage: starts_with_substring "string" "substring"
    [[ "$1" == "$2"* ]]
}

# Check if string ends with sub-string
pure.ends_with_substring() {
    # Usage: ends_with_substring "string" "substring"
    [[ "$1" == *"$2" ]] 
}

# ---
# ARRAYS
# ---

# Reverse an array
pure.reverse_array() {
    # Usage: reverse_array "array"
    shopt -s extdebug
    f()(printf '%s\n' "${BASH_ARGV[@]}"); f "$@"
    shopt -u extdebug
}

# Remove duplicate array elements
pure.remove_array_dups() {
    # Usage: remove_array_dups "array"
    declare -A tmp_array

    for i in "$@"; do
        [[ $i ]] && IFS=" " tmp_array["${i:- }"]=1
    done

    printf '%s\n' "${!tmp_array[@]}"
}

# Random array element
pure.random_array_element() {
    # Usage: random_array_element "array"
    local arr=("$@")
    printf '%s\n' "${arr[RANDOM % $#]}"
}

# Cycle through an array
pure.cycle() {
    printf '%s ' "${arr[${i:=0}]}"
    ((i=i>=${#arr[@]}-1?0:++i))
}

# ---
# FILE HANDLING
# ---

# Read a file to a string
pure.file_to_string() {
    # Usage file_to_string ".Xresources"
    printf '%s\n' "$(<"$1")"
}

# Read a file to an array (by line)
pure.file_to_array() {
    # Usage file_to_array ".Xresources"
    # Bash 4+
    mapfile -t file_data < "$1"
    printf '%s\n' "${file_data[@]}"
}

# Get the first N lines of a file
pure.head() {
    # Usage: head "n" "file"
    mapfile -tn "$1" line < "$2"
    printf '%s\n' "${line[@]}"
}

# Get the last N lines of a file
pure.tail() {
    # Usage: tail "n" "file"
    mapfile -tn 0 line < "$2"
    printf '%s\n' "${line[@]: -$1}"
}

# Get the number of lines in a file
pure.lines() {
    # Usage: lines "file"
    mapfile -tn 0 lines < "$1"
    printf '%s\n' "${#lines[@]}"
}

# Count files or directories in directory
pure.count() {
    # Usage: count /path/to/dir/*
    #        count /path/to/dir/*/
    printf '%s\n' "$#"
}

# Create an empty file
pure.touch() {
    >"$1"
}

# Extract lines between two markers
pure.extract() {
    # Usage: extract file "opening marker" "closing marker"
    while IFS=$'\n' read -r line; do
        [[ $extract && $line != "$3" ]] &&
            printf '%s\n' "$line"

        [[ $line == "$2" ]] && extract=1
        [[ $line == "$3" ]] && extract=
    done < "$1"
}

# ---
# FILE PATHS
# ---

# Get the directory name of a file path
pure.dirname() {
    # Usage: dirname "path"
    printf '%s\n' "${1%/*}/"
}

# Get the base-name of a file path
pure.basename() {
    # Usage: basename "path"
    : "${1%/}"
    printf '%s\n' "${_##*/}"
}

# ---
# INFORMATION ABOUT THE TERMINAL
# ---

# Get the terminal size in lines and columns (from a script)
pure.get_term_size() {
    # Usage: get_term_size

    # (:;:) is a micro sleep to ensure the variables are
    # exported immediately.
    shopt -s checkwinsize; (:;:)
    printf '%s\n' "$LINES $COLUMNS"
}

# Get the terminal size in pixels
pure.get_window_size() {
    # Usage: get_window_size
    printf '%b' "${TMUX:+\\ePtmux;\\e}\\e[14t${TMUX:+\\e\\\\}"
    IFS=';t' read -d t -t 0.05 -sra term_size
    printf '%s\n' "${term_size[1]}x${term_size[2]}"
}

# Get the current cursor position
pure.get_cursor_pos() {
    # Usage: get_cursor_pos
    IFS='[;' read -p $'\e[6n' -d R -rs _ y x _
    printf '%s\n' "$x $y"
}

# ---
# CONVERSION
# ---

# Convert a hex color to RGB
pure.hex_to_rgb() {
    # Usage: hex_to_rgb "#FFFFFF"
    #        hex_to_rgb "000000"
    : "${1/\#}"
    ((r=16#${_:0:2},g=16#${_:2:2},b=16#${_:4:2}))
    printf '%s\n' "$r $g $b"
}

# Convert an RGB color to hex
pure.rgb_to_hex() {
    # Usage: rgb_to_hex "r" "g" "b"
    printf '#%02x%02x%02x\n' "$1" "$2" "$3"
}

# ---
# OTHER
# ---

# Use read as an alternative to the sleep command
pure.read_sleep() {
    # Usage: sleep 1
    #        sleep 0.2
    read -rt "$1" <> <(:) || :
}

# Check if a program is in the user's PATH
pure.check_program_in_path() {
    type -p "$1" &>/dev/null
}

# Get the current date using strftime
pure.date() {
    # Usage: date "format"
    # See: 'man strftime' for format.
    printf "%($1)T\\n" "-1"
}

# Generate a UUID V4
pure.uuid() {
    # Usage: uuid
    C="89ab"

    for ((N=0;N<16;++N)); do
        B="$((RANDOM%256))"

        case "$N" in
            6)  printf '4%x' "$((B%16))" ;;
            8)  printf '%c%x' "${C:$RANDOM%${#C}:1}" "$((B%16))" ;;

            3|5|7|9)
                printf '%02x-' "$B"
            ;;

            *)
                printf '%02x' "$B"
            ;;
        esac
    done

    printf '\n'
}

# Progress bars
pure.bar() {
    # Usage: bar 1 10
    #            ^----- Elapsed Percentage (0-100).
    #               ^-- Total length in chars.
    ((elapsed=$1*$2/100))

    # Create the bar with spaces.
    printf -v prog  "%${elapsed}s"
    printf -v total "%$(($2-elapsed))s"

    printf '%s\r' "[${prog// /-}${total}]"
}

# Get the list of functions in a script
pure.get_functions() {
    # Usage: get_functions
    IFS=$'\n' read -d "" -ra functions < <(declare -F)
    printf '%s\n' "${functions[@]//declare -f }"
}

# Bypass shell aliases
# Example: \ls

# Run a command in the background
pure.bkr() {
    (nohup "$@" &>/dev/null &)
}
